### ISSUE TITLE
Only Date/Except Date

### ISSUE THREAD

**Issue by caJaeger** [mlipper/runt#15]
It is not clear to me from this documentation (without a very convoluted approach) how to create an expression that is "exactly this date, no repeat."

How might I go about saying:
```only March 3, 2018```

How might I go about saying:
```except March 3, 2018```

**Comment by mlipper** [comment]
Take a look at the `TemporalDate` class in `lib/runt/temporalexpression.rb`. It is an expression that matches an arbitrary date/time.

HTH,
Matt

P.S.
Sadly, I had already written what follows below before I stumbled across this answer....

Well, it's been a while since I've worked with this project so the short answer is: "I don't know but it's definitely possible". When I have a chance, I'll see if I can come up with a working example (BTW, step one for me will be reading through the code and tests since I've forgotten more than I remember about Runt and there's not much code to begin with).

 The longer answer is that in this implementation of Martin Fowler's design pattern, temporal expressions are composite objects (they can be added to each other and/or a larger collection) which when queried with specific dates, ranges or even other expressions, behave sort of like a language interpreter. When called, the target composite instance passes the given argument to each of its component temporal expressions asking "does this match?".

Given the above, I pretty sure one of the following will work with the existing code (WARNING: untested):
```ruby
# Reminder for Friday at 8:46 am, February 17th, 2017
reminder = PDate.min(2017,2,17,8,48,0)

# After a minute before and before a minute after - both non-inclusive
expr1 = AfterTE.new((reminder - 1), false) & BeforeTE.new ((reminder + 1), false)

# Every occurrence of Friday at 8:46 am, February 17th, 2017
expr2 = EveryTE.new(reminder)

# The framework's PDate (with minute precision) itself should work
expr3 = reminder
```

**Comment by caJaeger** [comment]
@mlipper Thanks for the explanation, in my review I had come across those After and Before expressions and figured that's what it would take! I suppose it wouldn't be terribly difficult to write an additional class that combines those at once. Thanks!

**Comment by mlipper** [comment]
Just to clarify: I believe `TemporalDate` is already exactly what you're looking for and you don't need the Before/AfterTE hack. I "found" it when I was trying to remember how to use my own code in writing the examples. I included them anyway for informational purposes...in any case, good luck and let me know

**Comment by caJaeger** [comment]
@mlipper Ah I misunderstood, thank you I will have a look!
